### ISSUE TITLE
Any binary update?

### ISSUE THREAD

**Issue by tobiasBora** [cedric-vincent/proot-static-build#5] opened 2018-03-14 00:35 UTC
Hello,

First thank you for this great tool. Then, I was wondering if it would not be useful to update the binaries here, since they did not change in the last 3 years, while the upstream code changed quite recently again.

Thank you again!

**Comment by oxr463** [comment] 2019-02-20 17:47
Duplicate of https://github.com/proot-me/PRoot/issues/127, closing.

**Closed as completed by oxr463** 2019-02-20 17:47 UTC
